DM-41049: Add matched color difference plots/metrics
lsst/analysis_tools pull request #156
Opened 2023-10-13 00:18 UTC by taranu

2024-03-19 15:08 UTC, natelust requested changes
There are lots of random little comments, but I am happy for you to use your judgement on most of this. The only real place I would like changes, or at least explanation is where you are introducing the dict types that need changes in pex_config. I think there are other ways of doing that as I mentioned and I would rather see them done that way instead of changing pex_config.

2024-03-19 17:36 UTC, taranu commented on python/lsst/analysis/tools/atools/diffMatched.py
> +    actions = ConfigDictField[str, PlotAction](doc="Named plot actions")
I do need to add PlotActions dynamically based on the config (specified colours). I figured a generic `DictPlotAction` would be useful (and should go somewhere else) and simpler/better than overriding produce, no?

2024-03-19 17:37 UTC, taranu commented on python/lsst/analysis/tools/atools/diffMatched.py
> +    actions = ConfigDictField[str, PlotAction](doc="Named plot actions")
If `actions` can be trivially replaced with a `ConfigurableActionStructField`, fine by me, though at some point I'd like to understand how/why it supports derived types while regular `ConfigDictField` doesn't.

2024-03-19 20:30 UTC, taranu commented on python/lsst/analysis/tools/actions/vector/vectorActions.py
> +    returnMillimags = Field[bool](doc="Use millimags or not?", default=True)
It's copypasta from `MagDiff` which dates back to `analysis_drp`, but sure, now is as good a time as any to fix them.

2024-03-19 20:39 UTC, taranu commented on python/lsst/analysis/tools/atools/genericProduce.py
> +        doc="Suffixes for y-axis keys to finalize summary stats for",
No, that's it... but I'll re-word it.

2024-03-19 20:40 UTC, taranu commented on python/lsst/analysis/tools/atools/genericProduce.py
> +                setattr(self.process.calculateActions, plural, statAction)
Whoops... good point.

2024-04-10 15:44 UTC, natelust approved these changes

2024-04-10 18:03 UTC, merged