DM-43334: Add dmL1AstroErr/dmL2AstroErr metric
lsst/analysis_tools pull request #222
Opened 2024-03-18 18:20 UTC by cmsaunders

2024-03-19 02:30 UTC, jeffcarlin commented
I agree with your choice of implementation. I confirmed that the code runs fine and produces reasonable results (though note that you'll need to change "RA" to "Dec" in the matchedVisitCore pipeline). Just a few small comments, and I think this is good to go!

2024-03-19 02:30 UTC, jeffcarlin requested changes
I agree with your choice of implementation. I confirmed that the code runs fine and produces reasonable results (though note that you'll need to change "RA" to "Dec" in the matchedVisitCore pipeline). Just a few small comments, and I think this is good to go!

2024-03-19 02:30 UTC, jeffcarlin commented on pipelines/matchedVisitQualityCore.yaml
> +      atools.stellarAstrometricSelfRepeatabilityDec.coordinate: 'RA'
'RA' --> 'Dec'

2024-03-19 18:24 UTC, cmsaunders commented on python/lsst/analysis/tools/atools/astrometricRepeatability.py
> +        self.process.buildActions.perGroupStd.buildAction.buildAction.vectorKey = "coord_dec"
Something has to be set, or the configuration validation fails. However, if I have this, I don't actually need the `else` part of the `if self.coordinate == "RA":.. ` statement in `finalize()`, so I took that out.

2024-03-19 18:25 UTC, cmsaunders commented on python/lsst/analysis/tools/atools/astrometricRepeatability.py
> +    level = Field[int](doc="Level 1 or 2 data product (1 or 2)", default=1)
Yes, good point! That should be more clear.

2024-03-20 19:59 UTC, jeffcarlin approved these changes
Looks good!

2024-03-21 15:05 UTC, merged